import type { LocalEvent } from "./types";

export const EVENTS: LocalEvent[] = [
  {
    id: "evt-01",
    title: "Sunset Rooftop Jazz & Vinyl Listening Session",
    venue: "The Wren Rooftop Lounge & Terrace",
    category: "Music",
    isoDate: "2026-09-19",
    dayLabel: "Fri, Sep 19",
    timeLabel: "7:00 PM",
    price: 25,
    distanceMiles: 1.2,
    imageAspect: "wide",
    description:
      "Watch the sun go down over the skyline while a live trio spins warm jazz standards between vinyl sets. Full bar and small plates available on the terrace.",
    isFeatured: true,
  },
  {
    id: "evt-02",
    title: "Taco Night",
    venue: "Rosa's",
    category: "Food",
    isoDate: "2026-09-19",
    dayLabel: "Fri, Sep 19",
    timeLabel: "6:00 PM",
    price: null,
    distanceMiles: 0.4,
    imageAspect: "square",
    description:
      "Free entry taco crawl featuring six neighborhood taquerias, live salsa music, and a horchata tasting bar.",
  },
  {
    id: "evt-03",
    title: "Family Day at the Botanical Gardens with Puppet Show",
    venue: "Ridgeline Botanical Gardens",
    category: "Family",
    isoDate: "2026-09-20",
    dayLabel: "Sat, Sep 20",
    timeLabel: "10:00 AM",
    price: 12,
    distanceMiles: 3.8,
    imageAspect: "tall",
    description:
      "A full day of garden trails, a hands-on butterfly tent, and an afternoon puppet show for younger kids on the great lawn.",
  },
  {
    id: "evt-04",
    title: "5K Fun Run",
    venue: "Riverside Park",
    category: "Sports",
    isoDate: "2026-09-20",
    dayLabel: "Sat, Sep 20",
    timeLabel: "8:00 AM",
    price: 15,
    distanceMiles: 2.1,
    imageAspect: "wide",
    description:
      "A flat, scenic loop along the river with a finish-line pancake breakfast. Strollers and dogs on leash welcome.",
  },
  {
    id: "evt-05",
    title: "Contemporary Ceramics & Fiber Arts Open Studio Night",
    venue: "Kiln House Collective Studios",
    category: "Arts",
    isoDate: "2026-09-20",
    dayLabel: "Sat, Sep 20",
    timeLabel: "5:30 PM",
    price: 8,
    distanceMiles: 1.6,
    imageAspect: "square",
    description:
      "Local ceramicists and fiber artists open their studios for an evening of demonstrations, small works for sale, and cider.",
  },
  {
    id: "evt-06",
    title: "Sunrise Kayak Tour",
    venue: "Blue Heron Boat Launch",
    category: "Outdoors",
    isoDate: "2026-09-21",
    dayLabel: "Sun, Sep 21",
    timeLabel: "6:30 AM",
    price: 40,
    distanceMiles: 5.4,
    imageAspect: "tall",
    description:
      "Guided kayak tour through the wetlands at first light, best chance of the week to spot herons and river otters. Gear included.",
  },
  {
    id: "evt-07",
    title: "Late Night Vinyl & Cocktails",
    venue: "Nocturne",
    category: "Nightlife",
    isoDate: "2026-09-19",
    dayLabel: "Fri, Sep 19",
    timeLabel: "10:00 PM",
    price: 10,
    distanceMiles: 0.9,
    imageAspect: "wide",
    description:
      "A resident DJ collective plays deep cuts on a warm analog sound system until close. Craft cocktail menu, 21+.",
  },
  {
    id: "evt-08",
    title: "Food Truck Rally",
    venue: "Commons Plaza",
    category: "Food",
    isoDate: "2026-09-20",
    dayLabel: "Sat, Sep 20",
    timeLabel: "11:00 AM",
    price: null,
    distanceMiles: 0.7,
    imageAspect: "square",
    description:
      "A dozen rotating food trucks, a beer garden, and live acoustic music on the plaza steps all afternoon.",
  },
  {
    id: "evt-09",
    title: "Indie Songwriters in the Round: An Evening of New Original Music",
    venue: "The Basement Listening Room",
    category: "Music",
    isoDate: "2026-09-21",
    dayLabel: "Sun, Sep 21",
    timeLabel: "8:00 PM",
    price: 18,
    distanceMiles: 2.9,
    imageAspect: "wide",
    description:
      "Four songwriters trade original songs and stories in an intimate, listening-room setting. Seated, limited capacity.",
  },
  {
    id: "evt-10",
    title: "Youth Soccer Clinic",
    venue: "Eastside Athletic Fields",
    category: "Sports",
    isoDate: "2026-09-20",
    dayLabel: "Sat, Sep 20",
    timeLabel: "9:00 AM",
    price: 20,
    distanceMiles: 4.5,
    imageAspect: "square",
    description:
      "Drop-in skills clinic for kids ages 6-12 led by local club coaches. Cleats and shin guards recommended.",
  },
  {
    id: "evt-11",
    title: "Gallery Walk",
    venue: "Arts District",
    category: "Arts",
    isoDate: "2026-09-18",
    dayLabel: "Thu, Sep 18",
    timeLabel: "6:00 PM",
    price: null,
    distanceMiles: 1.4,
    imageAspect: "tall",
    description:
      "A dozen galleries and studio spaces open their doors together for the monthly self-guided walk. Maps available at each stop.",
  },
  {
    id: "evt-12",
    title: "Trailhead Wildflower Hike and Native Plant Identification Walk",
    venue: "Copper Ridge Trailhead",
    category: "Outdoors",
    isoDate: "2026-09-21",
    dayLabel: "Sun, Sep 21",
    timeLabel: "9:00 AM",
    price: 5,
    distanceMiles: 7.2,
    imageAspect: "wide",
    description:
      "A naturalist-led moderate hike focused on late-season wildflowers and native plant identification. Bring water and sturdy shoes.",
  },
  {
    id: "evt-13",
    title: "Rooftop Silent Disco",
    venue: "Elevate Sky Bar",
    category: "Nightlife",
    isoDate: "2026-09-20",
    dayLabel: "Sat, Sep 20",
    timeLabel: "9:30 PM",
    price: 22,
    distanceMiles: 1.8,
    imageAspect: "square",
    description:
      "Three DJs, three channels, one rooftop. Wireless headphones provided at check-in, switch channels any time.",
  },
  {
    id: "evt-14",
    title: "Farmers Market",
    venue: "Old Mill Square",
    category: "Food",
    isoDate: "2026-09-20",
    dayLabel: "Sat, Sep 20",
    timeLabel: "8:00 AM",
    price: null,
    distanceMiles: 0.6,
    imageAspect: "tall",
    description:
      "Weekly farmers market with produce, baked goods, and a rotating lineup of local musicians on the square.",
  },
];
